version: '3.1'

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD:  postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  
  queue:
    image: redis:alpine
    ports:
      - "6379:6379"